### ISSUE TITLE
BootstrapCircleThumbnail custom size

### ISSUE THREAD

**Issue by sebitoelcheater** [Bearded-Hen/Android-Bootstrap#100]
Now you can just set "small medium large xlarge" as bct_size. Could you please make more options, or let this option be an integer? And please, could you let us set the white rounded margin?

Thank you guys! You did an amazing job.

**Comment by jamie-beardedhen** [comment]
This is in the works, in the meantime there are other libraries available which allow wrapping content e.g. CircleImageView

**Comment by jamie-beardedhen** [comment]
Fixed in 2.0.0
