### ISSUE TITLE
Converting to string: TypedValue{t=0x5/d=0x1202 a=1}

### ISSUE THREAD

**Issue by soft53ears** [Bearded-Hen/Android-Bootstrap#101]
When I use BootstrapButton in an ArrayAdapter, the LogCat prompt below warning:
**Converting to string: TypedValue{t=0x5/d=0x1202 a=1}**
I changed it to original Button, the warning disappeared.

**Comment by jamie-beardedhen** [comment]
Possibly related to this issue https://code.google.com/p/android/issues/detail?id=78322

Do you still see the issue when "Enable View Attribute Inspection" is disabled on the development device?

**Comment by soft53ears** [comment]
I actually didn't see this option on my cellphone...

**Comment by jamie-beardedhen** [comment]
@soft53ears does that mean you are still seeing the issue or not?

**Comment by soft53ears** [comment]
Yes, i'm still seeing this issue. But it seems this is not caused by this lib. Because after I changed it to some other code, the issue is still. I'm closing this issue.
