### ISSUE TITLE
Theme.AppCompat issue

### ISSUE THREAD

**Issue by msneujink** [Bearded-Hen/Android-Bootstrap#103]
When i add the bootstrap dependancy in my build.gradle `(compile 'com.beardedhen:androidbootstrap:+') `my app won't start anymore. I get the following error: 

`You need to use a Theme.AppCompat theme (or descendant) with this activity.`

Although my activity is actually using the AppCompatActivity
```java
public class LoginActivity extends AppCompatActivity {
````
My main theme:
````xml
<style name="AppBaseTheme" parent="Theme.AppCompat.Light.DarkActionBar"> 
````

What's wrong here?

**Comment by jamie-beardedhen** [comment]
The only thing I can think of is that the library appears to have a few unnecessary styles XML files, which are using Holo. If you don't have an overriding resource defined in your module, your app will automatically use the library's files.

It'd be great if you could test this out (by adding the library as a module & deleting the styles files). I'll try and find some spare time to deploy a fixed release if this is the case.

**Comment by msneujink** [comment]
Thanks, i will test this. I will report my findings here.

**Comment by msneujink** [comment]
I fixed it by deleting the values-v11 and values-v14 resource folders. It's working properly now :+1:

**Comment by jamie-beardedhen** [comment]
Thanks for the PR. Closing, an updated artifact should be available shortly.

**Comment by msneujink** [comment]
great! thanks
