### ISSUE TITLE
Hoping icon stacking can be use with this plugin

### ISSUE THREAD

**Issue by azizimusa** [Bearded-Hen/Android-Bootstrap#105]
We can use stack like this with html css 

```
<span class="fa-stack fa-lg">
  <i class="fa fa-square-o fa-stack-2x"></i>
  <i class="fa fa-twitter fa-stack-1x"></i>
</span>
```

Hope can use the same technique with this plugin.

**Comment by jamie-beardedhen** [comment]
I'm not familiar with HTML/CSS, does that code snippet just super-impose one icon on top of another? If that's the case, you could use a FrameLayout to achieve a similar effect.
