### ISSUE TITLE
Borderless buttons

### ISSUE THREAD

**Issue by noloman** [Bearded-Hen/Android-Bootstrap#106]
Does the library currently support any kind of borderless button?

I have a Bootstrap button with the icon pretty nicely rendered, but still I see the grey borders of a normal Android Button around.

**Comment by jamie-beardedhen** [comment]
FontAwesomeText should suit your needs, you can create an icon of arbitrary size & color, then apply any drawable to its background.

**Comment by renierdbruyn** [comment]
@jamie-beardedhen is there an example of how to do this?
