### ISSUE TITLE
BootstrapButton

### ISSUE THREAD

**Issue by patryk0493** [Bearded-Hen/Android-Bootstrap#107]
Hi, 

I'd like to use BootstrapButton feature and using my own font, but I can't do method setTypeface(TypeFace tf) on object BootstrapButton. How to solve problem ?

**Comment by jamie-beardedhen** [comment]
BootstrapButton is currently a compound view consisting of 2 FontAwesomeTexts & 1 TextView, which means it doesn't inherit TextView messages. As a workaround you could use reflection to access the TextView and set the typeface from there (or use the Caligraphy library to set a default font through your application).

**Comment by jamie-beardedhen** [comment]
Fixed in 2.0.0
