### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by hyorkim11** [Bearded-Hen/Android-Bootstrap#113]
Awesome stuff BH,

New updates pushed! awesome.
Just an issue with github dep, which version should we use for the latest ?
is it 2.1? what should I add on my gradle file dep?

**Comment by jamie-beardedhen** [comment]
compile 'com.beardedhen:androidbootstrap:2.0.0' should allow you to use the latest updates. Maven Central will take a while to sync, which is why the badge is currently displaying 1.2.3.

**Comment by hyorkim11** [comment]
Ah got it, now onto fixing all my layouts with the buttons in em!
thanks
