### ISSUE TITLE
Button Group

### ISSUE THREAD

**Issue by hyorkim11** [Bearded-Hen/Android-Bootstrap#114]
Button Group, set as vertical orientation, as of now doesn't seem to override rest of the widths for the child buttons.
I've implemented the Button Group (vertically) and see that all the child buttons have different widths depending on their texts

**Comment by jamie-beardedhen** [comment]
ButtonGroup extends LinearLayout, so you can just set its height to match_parent and assign the child views equal weights.

**Comment by hyorkim11** [comment]
thanks alot for the speedy reply!
