### ISSUE TITLE
Text Can't Be Aligned Top & Left

### ISSUE THREAD

**Issue by XinwenCheng** [Bearded-Hen/Android-Bootstrap#115]
Hi,

I'm not sure if this is an issue, but I didn't find solution from Internet and your sample code yet.

![bootstrapedittext](https://cloud.githubusercontent.com/assets/795334/10398171/0b33d774-6ede-11e5-9fe4-89305f6ce404.png)

As you can check the situation from above screenshot, when I set singleLine to false, and gravity to top or top|left, chartacters in edit text is still strat from left and vertical center, even I set textAlignment to gravity, it still doesn't work.

Would you please help to check this? Thanks very much!

**Comment by jamie-beardedhen** [comment]
[This line](https://github.com/Bearded-Hen/Android-Bootstrap/blob/master/AndroidBootstrap/src/main/java/com/beardedhen/androidbootstrap/BootstrapEditText.java#L80) is the issue, it automatically sets gravity to center_vertical. As a workaround you can call setGravity() until a new release gets pushed.

**Comment by redwerk** [comment]
Hi,

There is a pull request for this - https://github.com/Bearded-Hen/Android-Bootstrap/pull/121

Thanks!
