### ISSUE TITLE
Error on statement... App Crashes

### ISSUE THREAD

**Issue by nicknagi** [Bearded-Hen/Android-Bootstrap#116]
bLabel1 = (BootstrapButton)findViewById(R.id.bLabel1);
        bLabel2 = (BootstrapButton)findViewById(R.id.bLabel2);
        bLabel3 = (BootstrapButton)findViewById(R.id.bLabel3);
        bLabel1.setFontAwesomeIcon("fa_times");

on the last statement the app crashes.. ie, bLabel1.setFontAwesomeIcon("fa_times");
throws an android runtime exception

**Comment by hyorkim11** [comment]
we're gonna need more info on your code to help you
can you paste the logcat output atleast? :P

**Comment by jamie-beardedhen** [comment]
Have you followed the instructions in the README?
         ```TypefaceProvider.registerDefaultIconSets();```

**Comment by nicknagi** [comment]
TypefaceProvider.registerDefaultIconSets();

That did remove all errors. But, now no icon appears in my button. Earlier when I used  

bootstrap:bb_icon_right="fa-times"

 it used to work but now when I use 

app:fontAwesomeIcon="fa_times"  OR bLabel1.setFontAwesomeIcon("fa_times");

No icon of any sort is shown. What i want is a 'X' sign towards the right side of the button.

**Comment by jamie-beardedhen** [comment]
Please post XML & relevant code

**Comment by nicknagi** [comment]
<com.beardedhen.androidbootstrap.BootstrapButton
        android:layout_width="100dp"
        android:layout_height="50dp"
        android:text="a"
        app:bootstrapBrand="primary"
        app:roundedCorners="true"
        app:fontAwesomeIcon="fa_times"
        android:id="@+id/bLabel1"
        android:onClick="RemoveContact"
        android:layout_below="@+id/ivContact"
        android:layout_alignParentLeft="true"
        android:layout_alignParentStart="true"
        android:layout_marginTop="16dp"
        android:layout_marginLeft="24dp" />

    <com.beardedhen.androidbootstrap.BootstrapButton
        android:layout_width="100dp"
        android:layout_height="50dp"
        android:text="b"
        app:bootstrapBrand="primary"
        app:roundedCorners="true"
        app:fontAwesomeIcon="fa_times"
        android:id="@+id/bLabel2"
        android:onClick="RemoveContact"
        android:layout_alignTop="@+id/bLabel1"
        android:layout_toRightOf="@+id/bLabel1"
        android:layout_toEndOf="@+id/bLabel1"
        android:layout_marginLeft="16dp" />

    <com.beardedhen.androidbootstrap.BootstrapButton
        android:layout_width="wrap_content"
        android:layout_height="50dp"
        android:text=".. 5 more"
        app:bootstrapBrand="primary"
        app:roundedCorners="true"
        app:fontAwesomeIcon="fa_times"
        android:id="@+id/bLabel3"
        android:layout_alignTop="@+id/bLabel1"
        android:layout_toRightOf="@+id/bLabel2"
        android:layout_toEndOf="@+id/bLabel2"
        android:layout_marginLeft="16dp"
        android:onClick="ShowList" />

**Comment by nicknagi** [comment]
Can anyone help me with this issue ?

**Comment by jamie-beardedhen** [comment]
@nicknagi please post the Logcat output

**Comment by jamie-beardedhen** [comment]
Closing as not reproducible

**Comment by krzysiek-zgondek** [comment]
Have same problem.
Additionally i can input i.e. "{fa_android} text text" into bootstraptext and it works correctly.

**Comment by jamie-beardedhen** [comment]
@krzysiek-zgondek please open a new issue if you can reproduce a problem, with logcat output & code sample

**Comment by krzysiek-zgondek** [comment]
well i'm working on it right now, so if i will post new issue with or without solution after i give up
