### ISSUE TITLE
OnClickListener of BootstrapButton within BootstrapButtonGroup

### ISSUE THREAD

**Issue by cyrixmorten** [Bearded-Hen/Android-Bootstrap#119]
Any special method needed to capture click events of BootstrapButtons within BootstrapButtonGroup?

Within a recycleview I have: 

        // vBtnFinished is a BootstrapButton
        holder.vBtnFinished.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                ToastHelper.toast(context, "finish: " + task.getClientName());
            }
        });

        // vBtnWriteReport is a regular Button
        holder.vBtnWriteReport.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                ToastHelper.toast(context, "report: " + task.getClientName());
            }
        });

The report button 'vBtnWriteReport' fires just fine whereas 'vBtnFinished' does not.

Tried every workaround I could think of including 'android:descendantFocusability="blocksDescendants"' on the root of items being inflated.

On touch listener does fire .. however, multiple times it seems. 

Thanks in advance

**Comment by hyorkim11** [comment]
did you instantiate it correctly?
and as far as I remember, Bootstrap buttons have a slightly different way of instantiating.
```
b2 = (BootstrapButton) findViewById(R.id.b2);
```

**Comment by jamie-beardedhen** [comment]
@cyrixmorten does this only happen when the BootstrapButton is in a BootstrapButtonGroup?

**Comment by jamie-beardedhen** [comment]
It would also be helpful to know whether the buttonMode has been set to anything in your example code.

**Comment by cyrixmorten** [comment]
I just tried moving one of the buttons outside of the BootstrapButtonGroup and now it works, so seems  to have something to do with with BootstrapButtonGroup.

I set buttonMode="radio" in XML (residing inside a CardView wrapped in a LinearLayout if it matters):

                    <com.beardedhen.androidbootstrap.BootstrapButtonGroup
                        android:id="@+id/task_state_button_group"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:orientation="horizontal"
                        app:bootstrapBrand="info"
                        app:buttonMode="radio"
                        app:roundedCorners="true">


                        <com.beardedhen.androidbootstrap.BootstrapButton
                            android:id="@+id/task_state_aborted"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:clickable="true"
                            android:layout_weight="1"
                            android:text="@string/event_aborted" />

                        <com.beardedhen.androidbootstrap.BootstrapButton
                            android:id="@+id/task_state_finished"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:clickable="true"
                            android:layout_weight="1"
                            android:text="@string/event_finished" />
                    </com.beardedhen.androidbootstrap.BootstrapButtonGroup>   

Though, as setting these values in XML did not seem to have any effect, I also apply the setting in code:

    @Override
    public TaskViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        View itemView = LayoutInflater.
                from(parent.getContext()).
                inflate(R.layout.view_adapter_item_task, parent, false);

        final TaskViewHolder holder = new TaskViewHolder(itemView);

        holder.vBtnTaskGroup.setButtonMode(ButtonMode.RADIO);
        holder.vBtnTaskGroup.setShowOutline(false);
        holder.vBtnTaskGroup.setBootstrapSize(DefaultBootstrapSize.LG);

        return holder;
    }

After this appearance is correct and only the missing click triggering is missing.

**Comment by cyrixmorten** [comment]
Whoops didn't mean to close it.

I do believe that I can leave out the grouping and be fine, still an interesting issue though.
