### ISSUE TITLE
AwesomeTextView doesn't render icon's name with underscores

### ISSUE THREAD

**Issue by AlexanderKaraberov** [Bearded-Hen/Android-Bootstrap#120]
When I'm trying to set FA icon for `AwesomeTextView` like this `awesomeTextView.setFontAwesomeIcon("fa-group");` it renders `null`. But this works: `awesomeTextView.setFontAwesomeIcon("fa_group");` What is the purpose of these changes? In  the previous versions it worked fine with underscores in the name. FA docs also use [this notation](https://fortawesome.github.io/Font-Awesome/icons/)
P.S. Or maybe I missed description of these changes somewhere in the README?

**Comment by jamie-beardedhen** [comment]
Font Icons can now be specified as an XML enum attribute, and Android doesn't allow hyphens in value names:

https://github.com/Bearded-Hen/Android-Bootstrap/blob/master/AndroidBootstrap/src/main/res/values/attrs_font_awesome.xml

I'm marking this as a bug when the icon is a literal like "fa-group", as the library should be able to substitute the hyphen for an underscore.

**Comment by redwerk** [comment]
Hi,

There is a pull request for this - #122

Thanks!
