### ISSUE TITLE
Getting this Exception when using custom style. Small bug overall i love this lib

### ISSUE THREAD

**Issue by kisese** [Bearded-Hen/Android-Bootstrap#125]
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object
 at android.os.Parcel.writeSerializable(Parcel.java:1388)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Parcel.writeValue(Parcel.java:1335)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Parcel.writeArrayMapInternal(Parcel.java:638)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Bundle.writeToParcel(Bundle.java:1096)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Parcel.writeBundle(Parcel.java:663)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Parcel.writeValue(Parcel.java:1259)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Parcel.writeArrayMapInternal(Parcel.java:638)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Bundle.writeToParcel(Bundle.java:1096)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Parcel.writeBundle(Parcel.java:663)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Parcel.writeValue(Parcel.java:1259)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Parcel.writeSparseArray(Parcel.java:751)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Parcel.writeValue(Parcel.java:1287)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Parcel.writeArrayMapInternal(Parcel.java:638)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Bundle.writeToParcel(Bundle.java:1096)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Parcel.writeBundle(Parcel.java:663)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Parcel.writeValue(Parcel.java:1259)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Parcel.writeArrayMapInternal(Parcel.java:638)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Bundle.writeToParcel(Bundle.java:1096)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Parcel.writeBundle(Parcel.java:663)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:2974)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3458)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:815)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:104)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:194)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5537)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:  Caused by: java.io.NotSerializableException: com.enezaeducation.app.home.activity.MainActivity
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1344)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Parcel.writeSerializable(Parcel.java:1383)
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Parcel.writeValue(Parcel.java:1335) 
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Parcel.writeArrayMapInternal(Parcel.java:638) 
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313) 
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Bundle.writeToParcel(Bundle.java:1096) 
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Parcel.writeBundle(Parcel.java:663) 
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Parcel.writeValue(Parcel.java:1259) 
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Parcel.writeArrayMapInternal(Parcel.java:638) 
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313) 
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Bundle.writeToParcel(Bundle.java:1096) 
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Parcel.writeBundle(Parcel.java:663) 
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Parcel.writeValue(Parcel.java:1259) 
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Parcel.writeSparseArray(Parcel.java:751) 
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Parcel.writeValue(Parcel.java:1287) 
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Parcel.writeArrayMapInternal(Parcel.java:638) 
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313) 
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Bundle.writeToParcel(Bundle.java:1096) 
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Parcel.writeBundle(Parcel.java:663) 
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Parcel.writeValue(Parcel.java:1259) 
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Parcel.writeArrayMapInternal(Parcel.java:638) 
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313) 
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Bundle.writeToParcel(Bundle.java:1096) 
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Parcel.writeBundle(Parcel.java:663) 
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:2974) 
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3458) 
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:815) 
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:104) 
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:194) 
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5537) 
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372) 
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955) 
11-10 11:41:16.387 22315-22315/com.enezaeducation.app E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

**Comment by jamie-beardedhen** [comment]
Looks like the library is trying to serialize your activity, how have you defined your custom style?

**Comment by kisese** [comment]
I had defined it in java code as below:
start_quiz_button.setBootstrapBrand(new BootstrapBrand() {
            @Override
            public int defaultFill(Context context) {
                return context.getResources().getColor(R.color.eneza_blue);
            }

            @Override
            public int defaultEdge(Context context) {
                return context.getResources().getColor(R.color.eneza_blue);
            }

            @Override
            public int defaultTextColor(Context context) {
                return context.getResources().getColor(R.color.white);
            }

            @Override
            public int activeFill(Context context) {
                return context.getResources().getColor(R.color.eneza_blue_dark);
            }

            @Override
            public int activeEdge(Context context) {
                return context.getResources().getColor(R.color.eneza_blue_dark);
            }

            @Override
            public int activeTextColor(Context context) {
                return context.getResources().getColor(R.color.white);
            }

            @Override
            public int disabledFill(Context context) {
                return 0;
            }

            @Override
            public int disabledEdge(Context context) {
                return 0;
            }

            @Override
            public int disabledTextColor(Context context) {
                return 0;
            }
        });

**Comment by jamie-beardedhen** [comment]
The library is trying to serialise the Context object within the inner class, if you don't hold onto a reference (i.e. resolve colors in the constructor)  then it should work. Marked as a bug because the sample code needs updating

**Comment by kisese** [comment]
Ok, Let me try that, thank you for your help
