### ISSUE TITLE
Use custom color in AwesomeTextView

### ISSUE THREAD

**Issue by azizimusa** [Bearded-Hen/Android-Bootstrap#126]
How do i use my own color in AwesomeTextView? I tried with `android:textColor` but no go.

**Comment by jamie-beardedhen** [comment]
You can change the color by setting the BootstrapBrand to a custom implementation. Currently this can be done programmatically. See the BootstrapButton sample code for an example (the same principle applies to AwesomeTextView).

Also beware of #125, the sample code will be updated to reflect this shortly
