### ISSUE TITLE
BootstrapButton in BootstrapButtonGroup default check value

### ISSUE THREAD

**Issue by azizimusa** [Bearded-Hen/Android-Bootstrap#127]
It seem we can't set default check value for BootstrapButton inside BootstrapButtonGroup with button mode = radio. We need to click on it first. Is there any way I can set default value for it like "android:setChecked=true"

**Comment by redwerk** [comment]
Hi, 

I made a PR #137 for this issue.
Now BootstrapButonGroup has an attribute for default checked item.
Also BootstrapButton has an attribute that selects it in ButtonGroup in "radio" mode.

Thanks!
