### ISSUE TITLE
Android Studio Preview : AwesomeTextView

### ISSUE THREAD

**Issue by davcpas1234** [Bearded-Hen/Android-Bootstrap#129]
When using the new ```AwesomeTextView``` of ```v.2.0.0``` when previewing the activity Android Studio returns and instantiation error:

```java
java.lang.RuntimeException: Font 'fontawesome-webfont-v440.ttf' not properly registered
```

should this have been removed via ```View.isInEditMode()```?

**Comment by jamie-beardedhen** [comment]
Thanks for the report, it should indeed be removed in editmode.

**Comment by renierdbruyn** [comment]
This seems to still be an issue in 2.3.2

```java
Caused by: java.lang.RuntimeException: Font 'fontawesome-webfont-v470.ttf' not properly registered, please see the README at https://github.com/Bearded-Hen/Android-Bootstrap
```

**Comment by Akwarski** [comment]
add this:
TypefaceProvider.registerDefaultIconSets()
in onCreate before:
setContentView(...)

**Comment by Akwarski** [comment]
> This seems to still be an issue in 2.3.2
> 
> ```java
> Caused by: java.lang.RuntimeException: Font 'fontawesome-webfont-v470.ttf' not properly registered, please see the README at https://github.com/Bearded-Hen/Android-Bootstrap
> ```

add this:
TypefaceProvider.registerDefaultIconSets()
in onCreate before:
setContentView(...)
