### ISSUE TITLE
bct_minimal no longer working?

### ISSUE THREAD

**Issue by theunreal** [Bearded-Hen/Android-Bootstrap#138]
I'm trying to set the bct_ prefixed parameters and seem like they have no effect on my app image. The white border keep showing no matter what I'm trying.
`
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:bootstrap="http://schemas.android.com/tools">

    <com.beardedhen.androidbootstrap.BootstrapCircleThumbnail
        android:layout_width="50dp"
        android:layout_height="50dp"
        app:bootstrapBrand="danger"
        bootstrap:bct_minimal="true"
        android:layout_margin="3dp"
        />
`

**Comment by jamie-beardedhen** [comment]
The API has changed in v2.0.0, either revert to v1.2.3, or update to bootstrap:hasBorder="false". Check the example code or feel free to comment again if this doesn't solve your problem.
