### ISSUE TITLE
Error:Failed to resolve: com.android.support:support-annotations:23.1.1

### ISSUE THREAD

**Issue by abbasfisal** [Bearded-Hen/Android-Bootstrap#142]
when i add your dependecy in my gradle this error was appeared

i used this in my gradle:
 compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.android.support:recyclerview-v7:23.0.1'
    compile 'com.android.support:cardview-v7:23.0.1'

**Comment by SelimEmre** [comment]
you should change versions..

compile 'com.android.support:appcompat-v7:23.1.1'
compile 'com.android.support:recyclerview-v7:23.1.1'
compile 'com.android.support:cardview-v7:23.1.1'

**Comment by IgorGanapolsky** [comment]
What if I want to use `24.0.0-alpha1`?  It will throw a conflict error.

**Comment by jamie-beardedhen** [comment]
Define the annotations dependency explicitly, rather than transitively
