### ISSUE TITLE
Define button with text from string resource and icon(s) in XML

### ISSUE THREAD

**Issue by JeremyReynaud** [Bearded-Hen/Android-Bootstrap#145]
There is no way to define simple button with icon and label in XML with label coming from a string resource (I mainly for translation purpose).
The bootstrapText attribute do not accept string resource mixing with icons, only "hard coded" strings (I believe it is not possible on any text attribute on Android).
If you define both text and typicon/fontAwesomeIcon properties, text is ignored, only icon is rendered.
If you define both bootstrapText and typicon/fontAwesomeIcon properties, icon is ignored, only text is rendered.

**Comment by redwerk** [comment]
Hi @JeremyReynaud,

If i understand you correctly, you can't set button label with text and icon in the same time through strings.xml resource.
Just checked BootstrapButton with 
<string name="button_bootstrap_text">We {fa_heart} android bootstrap!</string>
from strings.xml, and  everything works fine, button renders with text and icon.

Could you please provide code snippet where you facing with this issue?

**Comment by JeremyReynaud** [comment]
Hi @redwerk,
Thanks for your answer! My bad, I was looking for a way to separate icon and text but I completely missed this easy way to do.
@jamie-beardedhen, I think you can close this issue, sorry.
