### ISSUE TITLE
BootstrapButton not clickable when bootstrapSize set to LG

### ISSUE THREAD

**Issue by MC0212** [Bearded-Hen/Android-Bootstrap#159]
When I declare a BootstrapButton in XML with attribute app:bootstrapSize="lg", the button is not clickable either by ButterKnife's onClick binding or by manually set the OnClickListener. When I remove the line app:bootstrapSize="lg", everything becomes normal.

**Comment by sangrime** [comment]
In case of me, If i set app:bootstrapSize value, every button is not working. I think it's not only "lg" problem.

**Comment by daniftodi** [comment]
I have the same problem

**Comment by andgeno** [comment]
I can confirm problems with app:bootstrapSize, too. It seems that only 'xs' and 'xl' do work properly.

**Comment by afan2009** [comment]
Got the same problems. Is it fixed? PS: 'android:enabled' is not available with 'lg' set.

**Comment by toantonyh** [comment]
OnClickListener doesn't work for me when I set app:bootstrapSize to md, lg, and sm.

OnClickListener DOES work for me when I set app:bootstrapSize to xl or xs. It also works when I just don't use app:bootstrapSize.

The device I'm testing it on is the Motorola Nexus 6.

**Comment by jamie-beardedhen** [comment]
This should be fixed in PR #168 

If this is essential to your usecase, please test out the PR, otherwise a release will be uploaded to Maven Central when I get a spare minute
