### ISSUE TITLE
Attribute "progress" has already been defined

### ISSUE THREAD

**Issue by shuufi** [Bearded-Hen/Android-Bootstrap#161]
I'm not able to import your library. Gradle failed to build with this error message `Error:(1620) Attribute "progress" has already been defined`. I'm currently using Support library v23.4.0. Thanks.

**Comment by jamie-beardedhen** [comment]
Can you post the full stacktrace? Sounds like the progress attribute has been defined elsewhere in one of your other dependencies.

**Comment by jamie-beardedhen** [comment]
Should be fixed in the latest version, reopen if you're still having problems.

**Comment by shuufi** [comment]
Fantastic. I'm able to load this into my project now. Thank you very much @jamie-beardedhen
