### ISSUE TITLE
Dependency Problem

### ISSUE THREAD

**Issue by vladf95** [Bearded-Hen/Android-Bootstrap#167]
I try to use this dependency:  compile 'com.github.Bearded-Hen:Android-Bootstrap:2.1.0'
My android studio says: Failed to resolve:  com.github.Bearded-Hen:Android-Bootstrap:2.1.0
What shoult I do? 
 repositories {maven { url "https://jitpack.io" }} is added in the bulid file.

**Comment by jamie-beardedhen** [comment]
Use the artefact from Maven Central, as described in the README, or fork your own repo & tag a release if you want to use Jitpack.
