### ISSUE TITLE
Setting BootstrapDropDown size via code or XML using strings.xml

### ISSUE THREAD

**Issue by feherbt** [Bearded-Hen/Android-Bootstrap#169]
Hi,
I need to change the size depend on device.

First I tired by string resource (values/strings.xml  and /values-sw800/strings.xml)
app:bootstrapSize="@string/bb_size_large"
Result:
Binary XML file line #114: Error inflating class <unknown>

No problem! I resolved by code using setBootstrapSize() method!
It is working on BootstrapButton but BootstrapDropDown has't got.

I don't want to duplicate the XML.

**Comment by feherbt** [comment]
clarification: if I put md/xl/... values in the strings.xml then the result is "Binary XML file Error inflating class"
BUT if I put 1,2..4 then everithing is ok!
Like that:
<string name="bb_size_normal_by_num">2</string>

**Comment by jamie-beardedhen** [comment]
This should be fixed in the latest version, please comment if you can still see this behaviour and I'll reopen
