### ISSUE TITLE
Dropdown not working on API 23 (6.0)

### ISSUE THREAD

**Issue by Djip** [Bearded-Hen/Android-Bootstrap#177]
Dropdown doesn't shows correctly on API 23 (Marshmallow - 6.0)

![screenshot_20160817-210748](https://cloud.githubusercontent.com/assets/10889230/17749644/dcf3149c-64be-11e6-865b-14ab1bb461f3.png)

**Comment by Djip** [comment]
Just tested on API 22, works fine.

**Comment by Djip** [comment]
And if i'm having over like 10-15 items, then it doesn't even show up. Guess this goes for all API's

**Comment by jamie-beardedhen** [comment]
BootstrapDropdown was mistakenly translating back to DP resulting in the wrong height, presumably that would be more apparent on devices running 6.0 as they'll probably have higher screen density. If this hasn't fixed it please reopen (I'm not particularly familiar with this part of the code)
