### ISSUE TITLE
Font icons View

### ISSUE THREAD

**Issue by khalid-mahmood** [Bearded-Hen/Android-Bootstrap#178]
Can You Generate Icons View for reference in sample app like 
[https://github.com/mikepenz/Android-Iconics](url)
<img src="https://raw.githubusercontent.com/mikepenz/Android-Iconics/develop/DEV/github/screenshots1.jpg" />

**Comment by JianxunRao** [comment]
The icons used in Android-Bootstrap are from "/assets/typicons-v207.ttf" and "/assets/MaterialIcons-Regular.ttf".And all typicons are available for reference in [http://www.typicons.com/](url) @khalid-mahmood

**Comment by jamie-beardedhen** [comment]
You can also create use other fonts by following these instructions:
https://github.com/Bearded-Hen/Android-Bootstrap/blob/master/ADD_FONT.md
