### ISSUE TITLE
BootstrapCircleThumbnail border color

### ISSUE THREAD

**Issue by antoniomerlin** [Bearded-Hen/Android-Bootstrap#179]
Can we change the BootstrapCircleThumbnail border color ?

**Comment by jamie-beardedhen** [comment]
Yes, by implementing your own BootstrapBrand, which uses the colours you desire: https://github.com/Bearded-Hen/Android-Bootstrap/wiki#custom-themes

You can then set the BootstrapBrand programmatically on the BootstrapThumbnail. I believe there is an example for doing this on a BootstrapButton in the sample application, the same principle applies to Thumbnails.

**Comment by antoniomerlin** [comment]
Can you provide me example if possible

**Comment by antoniomerlin** [comment]
After implementing custom style stille their is white border surrounding the image:

![6836378008160111318-account_id 1](https://cloud.githubusercontent.com/assets/4397319/18523854/adbbf5ec-7ad3-11e6-9ebd-0369cf751b66.png)


`profile_pic.setBootstrapBrand(new BootstrapBrand() {

            @ColorInt private final int defaultFill = Color.rgb(255,207,6);
            @ColorInt private final int defaultEdge = Color.rgb(255,207,6);
            @ColorInt private final int defaultTextColor = Color.rgb(255,207,6);
            @ColorInt private final int activeFill = Color.rgb(255,207,6);
            @ColorInt private final int activeEdge = Color.rgb(255,207,6);
            @ColorInt private final int activeTextColor = Color.rgb(255,207,6);
            @ColorInt private final int disabledFill = Color.rgb(255,207,6);
            @ColorInt private final int disabledEdge = Color.rgb(255,207,6);
            @ColorInt private final int disabledTextColor = Color.rgb(255,207,6);

            @Override
            public int defaultFill(Context context) {
                return defaultFill;
            }

            @Override
            public int defaultEdge(Context context) {
                return defaultEdge;
            }

            @Override
            public int defaultTextColor(Context context) {
                return defaultTextColor;
            }

            @Override
            public int activeFill(Context context) {
                return activeFill;
            }

            @Override
            public int activeEdge(Context context) {
                return activeEdge;
            }

            @Override
            public int activeTextColor(Context context) {
                return activeTextColor;
            }

            @Override
            public int disabledFill(Context context) {
                return disabledFill;
            }

            @Override
            public int disabledEdge(Context context) {
                return disabledEdge;
            }

            @Override
            public int disabledTextColor(Context context) {
                return disabledTextColor;
            }
        });`
