### ISSUE TITLE
[Question] How to text align left in BootstrapLabel

### ISSUE THREAD

**Issue by khalid-mahmood** [Bearded-Hen/Android-Bootstrap#182]
how can i set Text align left in BootstrapLabel ? 
android:gravity="left" not working.

**Comment by hyorkim11** [comment]
check parent container's alignments first

**Comment by khalid-mahmood** [comment]
@hyorkim11 its not dependent on parent.

**Comment by jamie-beardedhen** [comment]
@khalid-mahmood please post a minimal code example which can be used to reproduce the issue.

**Comment by khalid-mahmood** [comment]
<RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <com.beardedhen.androidbootstrap.BootstrapLabel
                android:id="@+id/product_price"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:bootstrapBrand="custom"
                app:bootstrapHeading="h6"
                app:roundedCorners="true"
                tools:text="Price" />
</RelativeLayout>

it show label with center text even if i use android:gravity="left"

**Comment by jamie-beardedhen** [comment]
android:gravity wasn't being respected for AwesomeTextView, BootstrapLabel, BootstrapButton, and BootstrapDropdown - a fix should be available shortly

**Comment by jamie-beardedhen** [comment]
Fixed in 2.3.1
