### ISSUE TITLE
BootstrapDropDown doesn't work in Preview

### ISSUE THREAD

**Issue by StNekroman** [Bearded-Hen/Android-Bootstrap#183]
![untitled](https://cloud.githubusercontent.com/assets/12896163/20834675/3ec4a328-b89f-11e6-8fbe-8ce51384cda6.png)

**Comment by jamie-beardedhen** [comment]
@StNekroman this should hopefully be fixed in 2.3.1, could you or someone else please check this out against the Maven artefact to make sure the Preview Editor isn't now failing at something else?

**Comment by StNekroman** [comment]
Yes, it is fixed.
