### ISSUE TITLE
How can I see all the codes from those layout elements?

### ISSUE THREAD

**Issue by mikhaelangelo** [Bearded-Hen/Android-Bootstrap#198]
I put the bootstrap on my Android code and work as well but I need to see all the code to use which layout elements. I've downloaded the boostrap apps and it's amazing but still missing a place to see the codes.

**Comment by jamie-beardedhen** [comment]
https://github.com/Bearded-Hen/Android-Bootstrap/tree/master/sample/src/main/java/com/fractalwrench/androidbootstrap/sample
