### ISSUE TITLE
How can I change the width of inclined lines? So that they become narrower or wider?

### ISSUE THREAD

**Issue by stovberpv** [Bearded-Hen/Android-Bootstrap#199]
I already imported the library into my application, but I could not find a place where I can adjust the width of the lines.
![image](https://user-images.githubusercontent.com/13037514/27007034-573f3208-4e4d-11e7-9478-3362293f1351.png)

Thanks in advance.

**Comment by jamie-beardedhen** [comment]
You can try setting the BootstrapSize on the progressbar, which will increase/decrease the width of the view. The width of the line == the view Height * 2.

If you require further control then it would probably be best to extend the class and override the draw method, or fork the library.
