### ISSUE TITLE
Gradient Buttons

### ISSUE THREAD

**Issue by theDazzler** [Bearded-Hen/Android-Bootstrap#27]
I'm making a new issue for each feature I added to discuss it because I added too many features at once in my fork. Here are the gradient buttons I added:

![2013-12-12 03 28 44](https://f.cloud.github.com/assets/684942/1730377/af61ffba-62dd-11e3-926a-b52263bf48ec.png)
![2013-12-12 03 28 21](https://f.cloud.github.com/assets/684942/1730378/af63ed8e-62dd-11e3-8e6a-c255bcbd2394.png)

To use a gradient button, you just set the attribute "gradient" to true in xml. There are gradient square buttons as well, just not pictured

**Comment by xpatient** [comment]
how to make "onClic and open new activity" on https://github.com/theDazzler/Android-Bootstrap.??
