### ISSUE TITLE
BootstrapButton created by code not visible

### ISSUE THREAD

**Issue by WestLink** [Bearded-Hen/Android-Bootstrap#37]
I create button by following code

  BootstrapButton button = new BootstrapButton(getApplicationContext());
  button.setText("Test");
  button.setBootstrapType("default");
  button.setLeftIcon("fa-heart");

  container.addView(button);

  but not visible.

  icon or text is still invisible after calling setText or setLeftIcon.

**Comment by qgadrian** [comment]
Still not fixed?

I tried to create a new button programatically but doesn't show text. 

XML workaround only works if you know the buttons, but if you don't know how many buttons will be created that doesn't help.

**Comment by jamie-beardedhen** [comment]
Feel free to create a PR if you can identify the issue. The XML workaround should work fine, just create a LayoutInflater then inflate views in a loop depending on how many buttons you need.

**Comment by huxqiray** [comment]
ياخشى بىلىمكەن

**Comment by allenc2014** [comment]
unfortunately, looks like this is still an issue with the latest version.

there are a lot of initialization code being called in the initialize() method, which is by-passed if XML is not used to create the button in the first place.

**Comment by jamie-beardedhen** [comment]
I believe I've fixed this in the feature-v4 branch, which is a major update for Bootstrap v4. Until then it's probably best to inflate from XML.

**Comment by Narengowda** [comment]
(newbiee)
can you tell me how to add feature-v4 dependencies in gradle ?

**Comment by jamie-beardedhen** [comment]
@Narengowda just install 2.0.0 of the library, this issue should be resolved in there
