### ISSUE TITLE
BootstrapCircleThumbnail with ImageView exposed

### ISSUE THREAD

**Issue by skunkwerk** [Bearded-Hen/Android-Bootstrap#60]
thanks for a great library!

I'd like to load an image into a BootstrapCircleThumbnail using the Picasso library, but I can't get access to the thumbnail's ImageView which I'd need to pass to Picasso like so:
Picasso.with(inflater.getContext()).load(group.profile_picture_url).into(imgView);

Any way the library could expose the ImageView?

keep up the great work

**Comment by jamie-beardedhen** [comment]
Fixed in 2.0.0
