### ISSUE TITLE
After updating the library from April to today's version, button suddenly not displayed correctly

### ISSUE THREAD

**Issue by kamilwlf** [Bearded-Hen/Android-Bootstrap#70]
right image gone, format changed(now center work) 
![all](https://cloud.githubusercontent.com/assets/7765963/5264383/8679b5fa-7a3a-11e4-9de1-a375e68313d7.jpg)

**Comment by ian2009** [comment]
- I also ran into this issue in my Nexus 4 (OS Android 5.0).
- After struggling a day of modifying and testing, following changes for the lblMiddle in the button Layout fixed my problem, hope it will be helpful:
**android:layout_width="0dp"**
**android:layout_weight="1"**
- The whole layout of the button
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:duplicateParentState="true"
    android:orientation="horizontal"
    android:paddingBottom="10dp"
    android:paddingTop="10dp">

    <TextView
        android:id="@+id/lblLeft"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center_vertical"
        android:paddingLeft="15dp"
        android:visibility="gone" />

    <TextView
        android:id="@+id/lblMiddle"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
        android:gravity="center_horizontal"
        android:paddingLeft="15dp"
        android:paddingRight="15dp"
        android:visibility="gone" 
        android:layout_weight="1"
    />

    <TextView
        android:id="@+id/lblRight"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center_vertical"
        android:paddingRight="15dp"
        android:visibility="gone" />

</LinearLayout>

- And I found an article is really helpful to understand it:
http://randomlytyping.com/blog/2014/2/9/matchparent-vs-fillparent

**Comment by jamie-beardedhen** [comment]
@ian2009 thanks for your fix, I'll try and test it out at some point over the next few days. Would you mind creating a PR?
