### ISSUE TITLE
Android Studio Preview Issue

### ISSUE THREAD

**Issue by Fmakdemir** [Bearded-Hen/Android-Bootstrap#76]
There was an issue with maven plugin version of Android-Bootstrap. After updating to Android Studio 1.0 its previews started giving `NullPointerException` because of `setBootstrapType`. I couldn't make any debugging without being able to see code so imported as module but now everything works fine.

Is there a way for me to test maven plugin so I can try to find why preview has been broken? If I can't preview it then it is like blind shooting views...

**Comment by mfkp** [comment]
Still experiencing this problem with AS 1.1 Preview 2.
Would be great to find a way to make it work with gradle.

**Comment by jamie-beardedhen** [comment]
I'm planning on setting up a local Maven repository at some point to investigate this issue. If anyone has any advice on how to do this or feels like investigating on their own machine, that would also be great.

**Comment by jamie-beardedhen** [comment]
I encountered a similar issue on another project and managed to stop the rendering popup by using View.isInEditMode(). This approach should work here, the only downside is that the rendering of the View might not be accurate if it can't load fonts etc.

**Comment by jamie-beardedhen** [comment]
Fixed as part of sample project creation

**Comment by DeathKnightMo** [comment]
My solution is download the source and import as a module in Android Studio. In BoostrapButton.java  line 185 ，there is multiple id (R.id.layout)  from bootstrap_button.xml and placeholder.xml, change android id to "layout_button" in bootstrap_button.xml and change it to “R.id.layout_button” in line 185, last  
build the project,it's will work fine.

**Comment by jamie-beardedhen** [comment]
@DeathKnightMo does this mean you're still seeing the issue in a recent version of the library?

**Comment by DeathKnightMo** [comment]
@jamie-beardedhen  yes, my android studio is v1.1.0 .

**Comment by jamie-beardedhen** [comment]
@DeathKnightMo weird, you're definitely using the 1.2.1 maven artefact? I've been using FontAwesomeText in an unrelated project without issue - is this only happening for certain views/layouts?

**Comment by simonwielens** [comment]
Seeing this issue with1.2.1 jar with android studio 1.1.0
I created a new project with Android Studio, min API level of 19, and started with a blank activity. I added the dependency and added the button xml & namespace from the readme.md and built the project

**Comment by jamie-beardedhen** [comment]
Is this still reproducible in v2.0.0?
