### ISSUE TITLE
AndroidStudio dependencies

### ISSUE THREAD

**Issue by YoungDroid** [Bearded-Hen/Android-Bootstrap#77]
Sorry, I'm a Newbie of Android.
I just add 
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.beardedhen:androidbootstrap:1.0.4'
}
but it show 
Error:Failed to find: com.beardedhen:androidbootstrap:1.0.4
How can I solve it

**Comment by yz253233154** [comment]
Oh.
I add 
    compile 'com.google.android.gms:play-services:6.1.71'
    compile 'com.beardedhen:androidbootstrap:+'
only error 
    compile 'com.beardedhen:androidbootstrap:+'
