### ISSUE TITLE
Plz don't let FontAwesomeText extends Framelayout

### ISSUE THREAD

**Issue by onewilk** [Bearded-Hen/Android-Bootstrap#81]
<LinearLayout
        android:layout_width="match_parent"
        android:layout_height="40dp"
        android:layout_centerInParent="true"
        android:gravity="center"
        android:background="@color/md_red_700"
        android:orientation="horizontal">

        <com.beardedhen.androidbootstrap.FontAwesomeText
            android:id="@+id/trash"
            android:layout_weight="1"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            app:fa_icon="fa-trash"
            android:gravity="center"
            android:layout_gravity="center"
            android:textColor="@color/md_white"
            android:textSize="26sp" />

        <com.beardedhen.androidbootstrap.FontAwesomeText
            android:id="@+id/share"
            android:layout_weight="1"
            android:gravity="center"
            android:layout_gravity="center"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            app:fa_icon="fa-qrcode"
            android:textColor="@color/md_white"
            android:textSize="26sp" />

        <com.beardedhen.androidbootstrap.FontAwesomeText
            android:id="@+id/copy"
            android:layout_weight="1"
            android:gravity="center"
            android:layout_gravity="center"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            app:fa_icon="fa-copy"
            android:textColor="@color/md_white"
            android:textSize="26sp" />
    </LinearLayout>
</RelativeLayout>

You know that the FontAwesomeText is extends Framelayout,so gravity and layout_gravity will not work...I have to write a lot of code to fix this problem...
just like this
<LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:gravity="center"
        android:orientation="horizontal">

        <LinearLayout
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_weight="1"
            android:gravity="center"
            android:padding="10dp"
            android:orientation="horizontal">

            <com.beardedhen.androidbootstrap.FontAwesomeText
                android:id="@+id/trash"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                app:fa_icon="fa-trash"
                android:textColor="@color/md_white"
                android:textSize="26sp" />
        </LinearLayout>

        <LinearLayout
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_weight="1"
            android:gravity="center"
            android:padding="10dp"
            android:orientation="horizontal">

            <com.beardedhen.androidbootstrap.FontAwesomeText
                android:id="@+id/share"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                app:fa_icon="fa-qrcode"
                android:textColor="@color/md_white"
                android:textSize="26sp" />
        </LinearLayout>

        <LinearLayout
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_weight="1"
            android:gravity="center"
            android:padding="10dp"
            android:orientation="horizontal">

            <com.beardedhen.androidbootstrap.FontAwesomeText
                android:id="@+id/copy"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                app:fa_icon="fa-copy"
                android:textColor="@color/md_white"
                android:textSize="26sp" />
        </LinearLayout>
    </LinearLayout>

It's so annoying...
Sorry for my poor english , just forget it...
I hope you know what i mean...Plz fix it,don't extends Framelayout

**Comment by jamie-beardedhen** [comment]
Ideally I think FontAwesomeText should extend TextView, as it doesn't seem to need any ViewGroup functionality. It would also be worth changing BootstrapButton so that button icons can also be animated/change color.

**Comment by jamie-beardedhen** [comment]
Fixed with latest version
