### ISSUE TITLE
Update to FontAwesome 4.3

### ISSUE THREAD

**Issue by jamie-beardedhen** [Bearded-Hen/Android-Bootstrap#83]
Need to update the library so that 4.3 icons can be used - this would be a good time to create a script that parses the cheatsheet and does it automatically.

**Comment by Fmakdemir** [comment]
I actually wrote a script that generates the font awesome map file it was in js but I can easily port it to Java python etc

**Comment by jamie-beardedhen** [comment]
I started writing a Python script last night and it's mostly done, just needs a bit of tidying up. This issue is essentially a reminder so I don't forget about it.
