### ISSUE TITLE
Strange display with AppCompat

### ISSUE THREAD

**Issue by SqualalaTeam** [Bearded-Hen/Android-Bootstrap#85]
Hello, can anyone help me please ?

When I use holo theme I have this result with BootstrapEditText

![capture du 2015-02-06 22 29 53](https://cloud.githubusercontent.com/assets/8436726/6087750/93864030-ae4f-11e4-9822-024de6ba1736.png)

And when I use Theme.AppCompat.Light.DarkActionBar, I have this strange result !

![capture du 2015-02-06 22 30 23](https://cloud.githubusercontent.com/assets/8436726/6087770/c228be5e-ae4f-11e4-847c-7fdeb90a14fa.png)

**Comment by jamie-beardedhen** [comment]
@SqualalaTeam have you changed anything else other than the theme, and does this occur when running the app on a real device? I assume the weird behaviour is the capitalisation?

**Comment by SqualalaTeam** [comment]
II have not changed anything, and I use the theme "Theme.AppCompat.Light.DarkActionBar" and yes this happens on real devices

**Comment by jamie-beardedhen** [comment]
Can you post the layout XML that causes this issue?

**Comment by SqualalaTeam** [comment]
<?xml version="1.0" encoding="utf-8"?>
<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:bootstrapbutton="http://schemas.android.com/apk/res-auto"
    xmlns:fontawesometext="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical" >
    
    <LinearLayout 
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">


    <com.beardedhen.androidbootstrap.BootstrapEditText
        android:id="@+id/editPseudoSign"
        android:layout_marginTop="20dp"
        android:inputType="text"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:hint="@string/nom_et_prenom"
        bootstrapbutton:be_roundedCorners="false"
        bootstrapbutton:be_state="primary"
        android:ems="10" >

        <requestFocus />
    </com.beardedhen.androidbootstrap.BootstrapEditText>

    <com.beardedhen.androidbootstrap.BootstrapEditText
        android:id="@+id/editMdpSign"
        android:inputType="textPassword"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:hint="@string/mot_de_passe"
        bootstrapbutton:be_roundedCorners="false"
        bootstrapbutton:be_state="primary"
        android:ems="10" />


    <com.beardedhen.androidbootstrap.BootstrapEditText
        android:id="@+id/editMdpConfirmeSign"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:inputType="textPassword"
        android:hint="@string/confirme_mdp"
        android:visibility="gone"
        bootstrapbutton:be_roundedCorners="false"
        bootstrapbutton:be_state="primary"
        android:ems="10" />

    <com.beardedhen.androidbootstrap.BootstrapEditText
        android:id="@+id/editEmailSign"
        android:inputType="textEmailAddress"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:hint="@string/email"
        bootstrapbutton:be_roundedCorners="false"
        bootstrapbutton:be_state="primary"
        android:ems="10" />
    
    <ProgressBar
        android:id="@+id/progressSign"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
        android:visibility="gone"
        />

    <Button
        android:id="@+id/btn_sign"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="@string/inscription" 
        android:background="@drawable/btn_connexion_conf"
        style="@style/ButtonText"/>
    
    
    </LinearLayout>

</ScrollView>

**Comment by jamie-beardedhen** [comment]
Looks like this is a problem with the theme, not the library, use the textAllCaps attribute
http://stackoverflow.com/questions/26958909/why-is-my-button-text-coerced-to-all-caps-on-lollipop

**Comment by SqualalaTeam** [comment]
Sorry it's my fault, but I'm talking about the BootstrapEditText and not the button !
