### ISSUE TITLE
Font issue with foreign chars 'æøå' at Buttons

### ISSUE THREAD

**Issue by cyrixmorten** [Bearded-Hen/Android-Bootstrap#86]
Hi

Seemed it happened only after upgrading to Android 5.0 so not sure where the problem lies.

Nevertheless, characters such as 'æøå' are positioned slightly lower than other chars, which looks a bit weird. Just wanted to let you know in case there is a obvious solution.

**Comment by jamie-beardedhen** [comment]
Which View are you observing this behaviour in? If you could post example code/screenshots to reproduce the issue, that would be helpful in determining whether this is an issue with the library or lollipop.

**Comment by cyrixmorten** [comment]
Sorry forgot to mention that it was with Buttons

Also forgot that I am using the fork adding gradients to Buttons, but cannot image that it has anything to do with it.

A screenshot is added below

![image](https://cloud.githubusercontent.com/assets/6650168/6186222/0566e98a-b377-11e4-85e6-d06d5f5efad8.png)

**Comment by jamie-beardedhen** [comment]
I'm closing this issue as it should belong in whichever fork you're using. It also seems probable to me that this is an Android 5.0 bug rather than anything to do with the library. As a starting point for investigation you could take bootstrap_button.xml and add it to your layout.
