### ISSUE TITLE
Failed to resolve: com.beardedhen:androidbootstrap:+ in Android Studio

### ISSUE THREAD

**Issue by krupalshah** [Bearded-Hen/Android-Bootstrap#87]
In Android STudio, Library isn't compiling and showing error as:
Error:(25, 13) Failed to resolve: com.beardedhen:androidbootstrap:+

**Comment by jamie-beardedhen** [comment]
This is an issue with your top-level build.gradle, it sounds like you haven't specified mavenCentral() as a repository.
