### ISSUE TITLE
Question about other FontAwesome assets

### ISSUE THREAD

**Issue by rohit-gandhe** [Bearded-Hen/Android-Bootstrap#88]
Hello,

Great utility, love it.

I just have a quick question about inclusion of other assets such as weather icons here: http://erikflowers.github.io/weather-icons/

How would one go about including these in the library?

Thanks,
Rohit

**Comment by jamie-beardedhen** [comment]
The library can only display FontAwesome icons at present. Adding extra icons would require setting the TextView typeface to the weather icon font, then setting the text to the correct icon unicode.

We will probably look into including this in the near future, along with adding in similar fonts.

**Comment by jamie-beardedhen** [comment]
Fixed in 2.0.0
