### ISSUE TITLE
fix doc: app:fa_icon="fa-heart" instead of fontawesometext:fa_icon="fa-heart"

### ISSUE THREAD

**Issue by younes0** [Bearded-Hen/Android-Bootstrap#89]
On https://github.com/Bearded-Hen/Android-Bootstrap/wiki/Font-Awesome-Text
It is said to use `fontawesometext:fa_icon="fa-heart`: it didn't work for me, I had to use  `app:fa_icon="fa-heart"`

**Comment by Fmakdemir** [comment]
It is actually a definition at the top of xml document you can set it to any name that is not in use for example if `LinearLayout` is root layout then you add below line to it:

```
<LinearLayout
	xmlns:bootstrapbutton="http://schemas.android.com/apk/res-auto"
	...
	>
		<com.beardedhen.androidbootstrap.FontAwesomeText
			bootstrapbutton:fa_icon="fa-heart"
			...
		/>
</LinearLayout>
```

You can change **bootstrapbutton** to **app** then you would write `app:fa_icon="fa-heart"

**Comment by jamie-beardedhen** [comment]
Closing (as explained above)

**Comment by younes0** [comment]
@Fmakdemir thanks for the explanation!
