### ISSUE TITLE
Adding Drawable Resources in bootstrap:bb_icon_right

### ISSUE THREAD

**Issue by harshdattani** [Bearded-Hen/Android-Bootstrap#90]
Hello, 
Superb utility, 
I want to add own drawable png in bb_icon_right in button, how to achieve this?

**Comment by jamie-beardedhen** [comment]
You would need to create your own fork of the library and replace the TextViews which currently display the icons with ImageViews. I'm labelling this as an enhancement as we may add this in as part of #88
