### ISSUE TITLE
How do i change button color?

### ISSUE THREAD

**Issue by EmpiteShehan** [Bearded-Hen/Android-Bootstrap#91]
How do i change button color?
If i can't can you add a option to change button color?

**Comment by jamie-beardedhen** [comment]
Setting the BootstrapType on a button changes its color, you can do this either through XML or code. As the purpose of the library is to use predefined colors/sizes from Bootstrap I don't see why there should be an option to change the button color - however, if there's a lot of popular demand I will reopen this. It should be relatively easy to create your own fork if you want to alter the backgrounds available.

**Comment by gnuhel** [comment]
@jamie-beardedhen 
+1 I would also like to see this feature in upcoming releases.

**Comment by Jiyda** [comment]
+1 Me too, I would like to see this feature.

**Comment by jamie-beardedhen** [comment]
Fixed in 2.0.0, use the BootstrapBrand interface to define custom styles

**Comment by azizimusa** [comment]
How do i define my own custom style and using it in `app:bootstrapBrand` ?

**Comment by SelimEmre** [comment]
Firstly, Library/Res/values/colors.xml add your style like: <color name="bootstrap_brand_deneme">#373a3c</color>, 
Secondly Library/Res/values/attrs.xml add custom syle name like:  <enum name="deneme" value="5"/>
After, com.beardedhan.androidbootstrap/api/defaults/DefaultBootstrapBrand.java define your style like DENEME(R.color.bootstrap_brand_deneme) and add to switch(attrValue) case 5:
                return DENEME; , I Hope understand me :)

**Comment by jamie-beardedhen** [comment]
Updates to README are required due to frequency of this question
