### ISSUE TITLE
Question about BootstrapEditText, set gravity not work!

### ISSUE THREAD

**Issue by luohaha** [Bearded-Hen/Android-Bootstrap#95]
When I use BootstrapEditText, I want to set "android:gravity="top|left" ", but it seem not working well.

**Comment by jamie-beardedhen** [comment]
Can you clarify what behaviour you're seeing with the attribute, and what you would expect to see? Is the problem still there if you use the same attributes for a plain Android EditText?

**Comment by luohaha** [comment]
The EditText which I use will contains multi lines. And I want to set the cursor on the top left corner. It work well when I used a plain Android EditText with "android:gravity="top|left" ". But it doesn't work well using BootstrapEditText, the cursor still on the center.

**Comment by jamie-beardedhen** [comment]
Should be fixed by #98, thanks for the PR
