### ISSUE TITLE
In API 21+, FontAwesome icons clip on right-side in 

### ISSUE THREAD

**Issue by TotzkePaul** [Bearded-Hen/Android-Bootstrap#97]
I am running android version 5.0.2 Nexus 7 tablet and even building the default example project, I found many icons (not all) would clip about a pixel or two on the right side. It does not see to be a padding issue but that android doesn't seem to know the exact size of the font element. I also tested this on my 4.4.4 Moto X, and that seems to work as expected. Only on my Nexus clips the icon. 

Solution 1 - increasing the font seems to fix most clippings:

    float fontSize = FontAwesome.DEFAULT_FONT_SIZE+0.5f;

Solution 2 - adding an extra space: 

    public void setLeftIcon(String leftIcon) {
        lblLeft.setText(FontAwesome.getUnicode(leftIcon)+" ");
    }

My sample buttons:

             <com.beardedhen.androidbootstrap.BootstrapButton
                    android:id="@+id/btn_clr"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_margin="10dp"
                    android:text="@string/btn_clr"

                    bootstrapbutton:bb_icon_left="fa-undo"
                    bootstrapbutton:bb_roundedCorners="true"
                    bootstrapbutton:bb_type="Danger" />

                <com.beardedhen.androidbootstrap.BootstrapButton
                    android:id="@+id/btn_login"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_margin="10dp"
                    android:text="@string/btn_login"
                    bootstrapbutton:bb_size="default"

                    bootstrapbutton:bb_icon_left="fa-user"
                    bootstrapbutton:bb_roundedCorners="true"
                    bootstrapbutton:bb_type="primary" />

                <com.beardedhen.androidbootstrap.BootstrapButton
                    android:id="@+id/btn_done"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_margin="10dp"
                    android:text="@string/btn_done"
                    bootstrapbutton:bb_size="default"

                    bootstrapbutton:bb_icon_left="fa-save"
                    bootstrapbutton:bb_roundedCorners="true"
                    bootstrapbutton:bb_type="success" />

**Comment by jamie-beardedhen** [comment]
Thanks for the detailed report, I'll test out both solutions and see which works best. I'm currently in the process of refactoring BootstrapButton to extend Button and use SpannableString, so depending on how long that takes, this issue might become obsolete.

**Comment by jamie-beardedhen** [comment]
Can anybody reproduce this on version 2.0.0 of the library?

**Comment by hyorkim11** [comment]
can we get the screenshot of the wanted outcome?
I may attempt a shot when i get the chance
