### ISSUE TITLE
button can not  get

### ISSUE THREAD

**Issue by jinlin516293816** [Bearded-Hen/Android-Bootstrap#99]
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:bootstrapbutton="http://schemas.android.com/apk/res-auto"
    android:id="@+id/ll_dialog_wifilogin"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:background="#fff"
    android:orientation="vertical"
    android:padding="25dp">
       <com.beardedhen.androidbootstrap.BootstrapButton
            android:id="@+id/bootbtn_wifi_cancel"
            android:layout_width="fill_parent"
            android:layout_height="wrap_content"
            android:layout_margin="10dp"
            android:text="@string/wifi_login_cancel"
            bootstrapbutton:bb_roundedCorners="true"
            bootstrapbutton:bb_size="default"
            bootstrapbutton:bb_type="default" />
</LinearLayout>

java

 View contentView = inflater.inflate(R.layout.dialog_wifi_login, null);
        //btn_wifi_login = (BootstrapButton) contentView.findViewById(R.id.btn_wifi_login);
       // btn_wifi_cancel = (BootstrapButton) contentView.findViewById(R.id.btn_wifi_cancel);
        tv_wifiname_text = (TextView) contentView.findViewById(R.id.tv_wifiname_text);
        tv_wifiname_text.setText(SSID);
        dialogPlus = new DialogPlus.Builder(getActivity())
                .setContentHolder(new ViewHolder(contentView))
                .setGravity(DialogPlus.Gravity.TOP)
                .setCancelable(false)
                .setOnDismissListener(new OnDismissListener() {
                    @Override
                    public void onDismiss(DialogPlus dialog) {
                    }
                })
                .setOnCancelListener(new OnCancelListener() {
                    @Override
                    public void onCancel(DialogPlus dialog) {

                    }
                })
                .setOnBackPressListener(new OnBackPressListener() {
                    @Override
                    public void onBackPressed(DialogPlus dialogPlus) {
                        dialogPlus.dismiss();
                    }
                })
                .setOnClickListener(new OnClickListener() {
                    @Override
                    public void onClick(DialogPlus dialogPlus, View dialogView) {
                        System.out.println(dialogView.getId()+"==="+R.id.bootbtn_wifi_cancel+"====="+(view.getId()==R.id.bootbtn_wifi_cancel));
                        switch (dialogView.getId()){
                            case R.id.bootbtn_wifi_cancel:
                                dialogPlus.dismiss();
                                break;
                            case R.id.btn_wifi_login:
                                //dialogPlus.dismiss();
                                System.out.print("111111111111111111");
                                break;
                            case R.id.btn_test:
                                System.out.print("8888888888888");
                            default:
                                System.out.println("66666666");
                        }
                    }
                })
                .create();

        dialogPlus.show();

I click this button ,but the button id not equals R.id.bootbtn_wifi_cancel

But  I test nomarl button 
 <Button android:layout_height="wrap_content"
            android:layout_width="wrap_content"
            android:text="111"
            android:id="@+id/btn_test"/>

I clik this button , the button id equals   R.id.btn_test , print "8888888888888" ,that's right;

**Comment by jamie-beardedhen** [comment]
Are you definitely setting the listener on the BootstrapButton? It would be helpful if you could shorten the code snippet down as it's hard to make sense of at the minute.
